#!/bin/bash

# usage: 
# dockerctl pull images.txt willdockerhub
# dockerctl tag images.txt willdockerhub
# dockerctl push images.txt willdockerhub

script_dir=$(dirname $(readlink -f $0))

images=`cat $2`
registry=$3

function log_debug() {
    echo -e "\033[34m$1 \033[0m"
}

function log_info() {
    echo -e "\033[36m$1 \033[0m"
}

function pullImage() {
    log_debug "#####pulling..........."
    icount=0   
    for image in $images
    do
        let icount+=1
        log_info "[$icount/$count]]pulling: $image"
        docker pull $image
        
    done
}

function retagImage() {
    log_debug "#####retaging..........."
    icount=0
    for image in $images
    do
        let icount+=1
        log_info "[$icount/$count]]retag: $image"
        image_name=${image##*/}
        docker tag $image $registry/$image_name
    done
}

function pushImage() {
    log_debug "#####pushing..........."
    icount=0
    for image in $images
    do
        let icount+=1
        image_name=${image##*/}
        log_info "[$icount/$count]]pushing: $registry/$image_name"
        docker push $registry/$image_name
    done
}

shift "$((OPTIND -1))"
subcommand=$1
case "$subcommand" in
  pull)
    pullImage
    exit 0
    shift
    ;;
  tag)
    retagImage
    exit 0
    shift
    ;;
  push)
    pushImage
    exit 0
    shift
    ;;
  run)
    pullImage
    retagImage
    pushImage
    exit 0
    shift
    ;;
esac
