# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "server" do |server|
    server.vm.box = "centos7"
    server.vm.hostname = "server.example.com"
    server.vm.network "private_network", ip: "192.168.94.12"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "server"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "client" do |client|
    client.vm.box = "centos7"
    client.vm.hostname = "client.example.com"
    client.vm.network "private_network", ip: "192.168.94.13"
    client.vm.provider "virtualbox" do |vb|
      vb.name = "client"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

end
