# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "ubuntuvm0" do |node|
    node.vm.box = "ubuntu1904"
    node.vm.hostname = "server.example.com"
    node.vm.network "private_network", ip: "172.43.43.10"
    node.vm.provider "virtualbox" do |v|
      v.name = "ubuntuvm0"
      v.memory = 2048
      v.cpus = 1
    end
  end
end
