# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos1907" 
  config.vm.host_name = "centos"
  config.vm.network "forwarded_port", guest: 80, host: 8080 
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "./data", "/usr/share/nginx/html", owner: "root", group: "root"
  config.vm.provider "virtualbox" do |vb|
	vb.name = "centos1907-test"
    vb.memory = 2048
    vb.cpus = 1
  end
  config.vm.provision "shell", inline: <<-SHELL
    setenforce 0
    sed -i --follow-symlinks 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux
    curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
    yum update -y
    yum install -y vim wget
    yum install -y epel-release
    yum install -y nginx
    systemctl enable --now nginx
  SHELL
end