# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # config.vm.provision "shell", path: "bootstrap.sh"
  
  NodeCount = 3

  (1..NodeCount).each do |i|
    config.vm.define "centosvm0#{i}" do |node|
      node.vm.box = "centos7"
      node.vm.hostname = "centosvm0#{i}.example.com"
      node.vm.network "private_network", ip: "172.16.1#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "centosvm0#{i}"
        v.memory = 4096
        v.cpus = 2
      end
    end
  end

end
